### ISSUE TITLE
Changing pattern size doesn't update Arrangement

### ISSUE THREAD

**Issue by kdx2a** [YuriSizov/boscaceoil-blue#25]
Changing pattern size does not update Arrangement, which results in a need to manually update each pattern to have them draw correctly. Also, patterns longer than the current pattern size draw out of bounds after update.

Steps to reproduce:
1. Create a 4:16 pattern
2. Change pattern size to 4:4
3. See than the pattern visual wasn't updated in the Arrangement tab
4. Place or remove one note from the pattern
5. See than the pattern visual goes out of the box in the Arrangement tab

**Comment by YuriSizov** [comment]
Hey, thanks for the report! Yes, indeed, patterns in the arrangement tab are no always updated immediately with some changes. I find it's a minor annoyance most of the time, but I agree that it needs to be fixed. To clarify, do you change the tab back and forth between FILE and ARRANGEMENT between steps 2 and 3? Or do you use the undo for this, without leaving the ARRANGEMENT tab?

By the way, you don't actually need to draw notes. Just clicking on any pattern in the arrangement should trigger a redraw that'll fetch the new data. Hovering over the pattern dock to the right should update it too.

----

As for notes going out of bounds, that is totally normal. You can in fact draw notes that extend the boundaries of the pattern, and that's by design. You may want to do this to have a certain duration of decay/residual sound instead of a more abrupt cut off. This is respected by the WAV exporter, by the way, and you should get the full sound when you export your song.

**Comment by YuriSizov** [comment]
> As for notes going out of bounds, that is totally normal.

After some testing, I see what you mean. The notes which no longer fit the pattern size are drawn in the preview anyway. That is indeed a bug and not a part of the feature that I described before.
