### ISSUE TITLE
Accidently erase part of sequence by changing to simple drums 

### ISSUE THREAD

**Issue by quirkylemon** [YuriSizov/boscaceoil-blue#6]
if you have have any notes in the upper range of the sequencer like hi hats when using sion drums it is possible to erase them without a warning by changing to simple drums.

**Comment by YuriSizov** [comment]
Yes, this is true! The same happens when you change scale, which is a deliberate behavior present in the original app too. I agree that this can be problematic. What do you think the flow should be?

On a bigger scale, maybe there should be an undo-redo system, so nothing is permanently destructive. That would be a nice feature for a future update.

**Comment by darkhog** [comment]
Undo/redo, but until that's implemented a warning dialogue if the program detects notes that would be deleted on scale/drum change to confirm action would be good enough.

**Comment by YuriSizov** [comment]
Forgot to close it last week. As of https://github.com/YuriSizov/boscaceoil-blue/commit/13e067228d08ca0af4d5b652d3a26fec904594af we have the undo redo system, which should cover all the inconveniences related to destructive actions. Available in beta 2!
