### ISSUE TITLE
Provide a web version

### ISSUE THREAD

**Issue by darkhog** [YuriSizov/boscaceoil-blue#8]
Since Godot supports web exports, how about a web version of the program to play around with?

**Comment by YuriSizov** [comment]
Hey, web version is definitely in the books!

I mentioned it here and there, but the long and the short of it is: it just needs a bit of time to polish, and it will only work in Chrome-ish browsers (due to Godot limitations). Firefox may also be possible in the future, since Mozilla devs have been looking into a bug on their side that prevents it now. On my end, I need to work on the I/O part, how saving and loading files works. The music making part itself has already been vetted and works just fine on web.

You can see the same synthesizer running on web here:
https://humnom.net/demos/gdsion/
_(it may take a hot minute to load, and, again, Chrome and Chrome-likes only)_

**Comment by YuriSizov** [comment]
Time for an update! I've been working on the web version this week, and we are in a pretty good shape.

As mentioned before, the synthesizer itself has full support of the platform, and the front-end of the application is perfectly fine on web as well thanks to Godot's cross-portability. The main concern of mine was the file I/O, but I managed to implement the necessary changes and they appear to be working perfectly fine in both Chrome and recent versions of Firefox.

<img width="904" alt="NVIDIA_Overlay_2024-12-18_14-27-48" src="https://github.com/user-attachments/assets/5867dbf4-26c0-4b22-91ac-13adb4b9093c" />

And yes, both Chrome-like browsers and Firefox are now supported, as the Firefox team has fixed a bug on their end that would break Godot projects that use GDExtension from loading. Safari is still amiss on the supported list due to their own issues.

I'm also working on a landing page that would appear before the application is loaded, so potential issues can be prevented and explained. With a couple more changes, I think it'll all be ready and I'll make it available for public testing.

<img width="964" alt="chrome_2024-12-18_17-45-02" src="https://github.com/user-attachments/assets/af6f3f99-d1af-4da5-9029-4782a5c305ba" />
<img width="968" alt="chrome_2024-12-18_17-43-57" src="https://github.com/user-attachments/assets/874b7b4d-e58c-470f-907b-d5820cc1d4f5" />

**Comment by YuriSizov** [comment]
I made the current build of 3.1 available here:
https://humnom.net/apps/boscaceoil/beta/

Do let me know if you have any issues loading it.

**Comment by YuriSizov** [comment]
With some help I've tested and fixed it up a bunch. Also improved the landing page. The link is still the same as above!

I still need to include the new version into the build system for CI and releases. Once that is done, this task will be complete. I will probably host Bosca Ceoil myself on the same domain (sans `/beta/`). It may work on itch.io as well, but it needs further testing as there are some limitations when it comes to third-party platforms and web hosting.

Here's how the landing looks now:

<img width="1280" alt="chrome_2024-12-19_19-26-38" src="https://github.com/user-attachments/assets/32a6dd7f-8e3c-4dd0-a1b1-efb329cb7a85" />
<img width="1280" alt="chrome_2024-12-19_19-27-29" src="https://github.com/user-attachments/assets/d960d178-a6c2-40b5-8322-245ab5bc5a23" />

**Comment by YuriSizov** [comment]
Web version is now fully implemented as of https://github.com/YuriSizov/boscaceoil-blue/commit/4fba1e0aa9e27d4dc2e94c7d5683a8abf83ee1a2!
